<?php
return [
    'ask_doctor' => \App\Commands\AskDoctor::class,
    'ask_another' => \App\Commands\AnotherQuestions::class,
    'back_ask_doctor' => \App\Commands\AskDoctor::class,
    'back_ask_another' => \App\Commands\AnotherQuestions::class,
    'bServ' => \App\Commands\ServiceList::class,

    'service_list' => \App\Commands\ServiceList::class,
    'next_cert' => \App\Commands\Certificates::class,
    'chat' => \App\Commands\Contacts::class,
    'service_a' => \App\Commands\ServiceList::class,
    'c0' => \App\Commands\ServiceList\DentalTreatment::class,
    'templ_0' => \App\Commands\ServiceList\DentalTreatment::class,
    'sl_1_action' => \App\Commands\ServiceList\TeethAlignment::class,
    'sl_2_action' => \App\Commands\ServiceList\AestheticDentistry::class,
    'bracA' => \App\Commands\ServiceList\TeethAlignment::class,
    'elinA' => \App\Commands\ServiceList\TeethAlignment::class,
    'platA' => \App\Commands\ServiceList\TeethAlignment::class,
    'aesthetic_action' => \App\Commands\ServiceList\AestheticDentistry::class,
    'restoration_action' => \App\Commands\ServiceList\AestheticDentistry::class,
    'sl_3_action' => \App\Commands\ServiceList\Hygiene::class,
    'appointment' => \App\Commands\OfferAppointment::class,
    'app_back' => \App\Commands\OfferAppointment::class,
    'few_app' => \App\Commands\OfferAppointment::class,
    'few_app_ready' => \App\Commands\OfferAppointment::class,
    'new_record' => \App\Commands\CreateAppointment::class,
    'how_long' => \App\Commands\OfferAppointment::class,
    'dont_remem' => \App\Commands\OfferAppointment::class,
    'my_record' => \App\Commands\MyRecords::class,
    'records_back' => \App\Commands\MyRecords::class,
    'change_record_time' => \App\Commands\MyRecords::class,
    'cancel_record' => \App\Commands\MyRecords::class,
    'cancel_confirm' => \App\Commands\MyRecords::class,
    'how_long_rec' => \App\Commands\MyRecords::class,
    'new_record_rec' => \App\Commands\MyRecords::class,
    'will_be' => \App\Commands\RecordConfirm::class,
    'mapp' => \App\Commands\OfferAppointment::class,
];