<?php
return [
    'skip' => \App\Commands\MainMenu::class,
    'main_menu' => \App\Commands\MainMenu::class,

    'start' => \App\Commands\AskPhonenumber::class,
    'enter_birthday' => \App\Commands\AskBirthday::class,
    'profile' => \App\Commands\Profile::class,

    'change_fio' => \App\Commands\Profile::class,
    'change_phone_number' => \App\Commands\Profile::class,

    'contact_us' => \App\Commands\Contacts::class,

    'how_to_drive' => \App\Commands\Address::class,
    'public_transport' => \App\Commands\Address::class,
    'car_transport' => \App\Commands\Address::class,

    'faq' => \App\Commands\FAQ::class,
    'to_doctor' => \App\Commands\AskDoctor::class,
    'ask_doctor_1' => \App\Commands\AskDoctor::class,
    'ask_doctor_2' => \App\Commands\AskDoctor::class,
    'ask_doctor_3' => \App\Commands\AskDoctor::class,
    'ask_doctor_4' => \App\Commands\AskDoctor::class,
    'ask_doctor_5' => \App\Commands\AskDoctor::class,
    'ask_doctor_6' => \App\Commands\AskDoctor::class,
    'another_questions' => \App\Commands\AnotherQuestions::class,
    'ask_another_1' => \App\Commands\AnotherQuestions::class,
    'ask_another_2' => \App\Commands\AnotherQuestions::class,
    'ask_another_3' => \App\Commands\AnotherQuestions::class,
    'ask_another_4' => \App\Commands\AnotherQuestions::class,
    'ask_another_5' => \App\Commands\AnotherQuestions::class,
    'ask_another_6' => \App\Commands\AnotherQuestions::class,

    'about_doctor' => \App\Commands\AboutDoctor::class,
    'certificates' => \App\Commands\Certificates::class,
    'next_cert' => \App\Commands\Certificates::class,

    'my_records' => \App\Commands\MyRecords::class,
    'cancel_record' => \App\Commands\MyRecords::class,
    'change_record_time' => \App\Commands\MyRecords::class,
    'cancel_confirm' => \App\Commands\MyRecords::class,
    'dont_remember' => \App\Commands\MyRecords::class,

    'service_list' => \App\Commands\ServiceList::class,
    'teml_0' => \App\Commands\ServiceList\DentalTreatment::class,
    'c0' => \App\Commands\ServiceList\DentalTreatment::class,
    'brec' => \App\Commands\ServiceList\TeethAlignment::class,
    'ele' => \App\Commands\ServiceList\TeethAlignment::class,
    'plast' => \App\Commands\ServiceList\TeethAlignment::class,
    'platTempl' => \App\Commands\ServiceList\TeethAlignment::class,
    'bracPhoto' => \App\Commands\ServiceList\TeethAlignment::class,
    'bracCost' => \App\Commands\ServiceList\TeethAlignment::class,
    'bracTempl' => \App\Commands\ServiceList\TeethAlignment::class,
    'eleTempl' => \App\Commands\ServiceList\TeethAlignment::class,
    'eleCost' => \App\Commands\ServiceList\TeethAlignment::class,
    'platPhoto' => \App\Commands\ServiceList\TeethAlignment::class,
    'bracConsultCost' => \App\Commands\ServiceList\TeethAlignment::class,
    'bracPrinc' => \App\Commands\ServiceList\TeethAlignment::class,
    'otbel' => \App\Commands\ServiceList\AestheticDentistry::class,
    'restavr' => \App\Commands\ServiceList\AestheticDentistry::class,
    'vinir' => \App\Commands\ServiceList\AestheticDentistry::class,
    'otbelTempl' => \App\Commands\ServiceList\AestheticDentistry::class,
    'restavrTempl' => \App\Commands\ServiceList\AestheticDentistry::class,
    'get_notification' => \App\Commands\ServiceList\Hygiene::class,
    'bracCostAbout' => \App\Commands\ServiceList\TeethAlignment::class,

    'mapp' => \App\Commands\OfferAppointment::class,
    'app_back' => \App\Commands\OfferAppointment::class,
    '0o' => \App\Commands\OfferAppointment::class,
    '1o' => \App\Commands\OfferAppointment::class,
    '2o' => \App\Commands\OfferAppointment::class,
    '3o' => \App\Commands\OfferAppointment::class,
    '4o' => \App\Commands\OfferAppointment::class,
    '6o' => \App\Commands\OfferAppointment::class,
    '7o' => \App\Commands\OfferAppointment::class,
    '8o' => \App\Commands\OfferAppointment::class,
    '9o' => \App\Commands\OfferAppointment::class,
    '10o' => \App\Commands\OfferAppointment::class,
    '11o' => \App\Commands\OfferAppointment::class,
    'another_days' => \App\Commands\OfferAppointment::class,

    'Посмотреть другие дни недели⬇' => \App\Commands\OfferAppointment::class,
    'Отписаться от рассылки' => \App\Commands\UnSetNotif::class,
];
